name: The Grid
favicon: "https://passport.thegrid.io/favicon.ico"
layout_spectrum: 0.62
typography_spectrum: 0.3919
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: "295556487279234"
  twitter: l4y05
opengraph:
  appId: "1517733501804443"
  image: "http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png"
  type: website
color:
  brandColors:
    - '#071d27'
    - '#f3cb6d'
    - '#938450'
    - '#fcfbfd'
    - '#525253'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
