name: The Grid
title: Join the Evolution
favicon: 'https://passport.thegrid.io/favicon.ico'
layout_spectrum: 0.7
typography_spectrum: 0.3918
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: '295556487279234'
  twitter: l4y05
opengraph:
  image: 'http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png'
  type: website
  appId: '1517733501804443'
color:
  brandColors:
    - '#071d27'
    - '#f3cb6d'
    - '#938450'
    - '#fcfbfd'
    - '#525253'
  brandStrength: 0
  lightness: 0.23
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: sales
    item: 98c08669-5ed5-4e19-849a-4ba4dd308798
