name: The Grid
favicon: 'https://passport.thegrid.io/favicon.ico'
layout_spectrum: 0
typography_spectrum: 0.13504
title: Join the Evolution
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: '295556487279234'
  twitter: l4y05
opengraph:
  image: 'http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png'
  type: website
  appId: '1517733501804443'
color:
  brandColors:
    - '#ffe54c'
    - '#94b7b9'
    - '#ccffff'
    - '#1b1b21'
    - '#687e82'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: sales
    item: 98c08669-5ed5-4e19-849a-4ba4dd308798
    url: null
