name: The Grid
favicon: 'https://passport.thegrid.io/favicon.ico'
layout_spectrum: 0.64322
typography_spectrum: 0.22450116905383766
style: the-composer
title: Join the Evolution
navigation:
  - url: 'https://blog.thegrid.io/'
    name: Blog
  - url: 'https://support.thegrid.io/'
    name: Support
  - url: 'http://status.thegrid.io/'
    name: Status
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: '295556487279234'
  twitter: l4y05
opengraph:
  image: 'http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png'
  type: website
  appId: '1517733501804443'
color:
  brandColors:
    - '#3bd1dd'
    - '#f99d98'
    - '#fefefe'
    - '#0c7da7'
    - '#0b3f87'
  brandStrength: 0.6305408640764654
  lightness: 0.6788501695264131
  saturation: 0.8077160366810858
  rhythmicContrast: 0.25
purpose:
  - name: sales
    item: 98c08669-5ed5-4e19-849a-4ba4dd308798
    url: null
