layout_spectrum: 0.9202480947133154
typography_spectrum: 0.20952483941800892
color:
  brandColors:
    - '#EC454E'
    - '#281225'
    - '#FFFFFF'
    - '#25B9B0'
    - '#897C87'
  brandStrength: 0.870523275109008
  lightness: 0.4235451032873243
  saturation: 0.6333806128241122
  rhythmicContrast: 0.9051852924749255
name: Grid
favicon: 'https://passport.thegrid.io/favicon.ico'
title: Join the Evolution
navigation:
  - url: 'https://blog.thegrid.io/'
    name: Blog
    type: external
  - url: 'https://support.thegrid.io/'
    name: Support
    type: external
  - url: 'http://status.thegrid.io/'
    name: Status
    type: external
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: '295556487279234'
  twitter: l4y05
opengraph:
  image: 'http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png'
  type: website
  appId: '1517733501804443'
purpose: []
