layout_spectrum: 0.835347325541079
typography_spectrum: 0.38405128568410873
color:
  brandColors:
    - '#0ECCD8'
    - '#142C4D'
    - '#FFFFFF'
    - '#FF667F'
    - '#9D8EA2'
  brandStrength: 0.6235902858898044
  lightness: 0.26987025258131325
  saturation: 0.8725575250573456
  rhythmicContrast: 0.030576986027881503
name: The Grid
favicon: 'https://passport.thegrid.io/favicon.ico'
title: Join the Evolution
navigation:
  - url: 'https://blog.thegrid.io/'
    name: Blog
    type: external
  - url: 'https://support.thegrid.io/'
    name: Support
    type: external
  - url: 'http://status.thegrid.io/'
    name: Status
    type: external
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: '295556487279234'
  twitter: l4y05
opengraph:
  image: 'http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png'
  type: website
  appId: '1517733501804443'
purpose: []
