name: Grid
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#071d27'
    - '#f3cb6d'
    - '#938450'
    - '#fcfbfd'
    - '#525253'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
