typography_spectrum: 0.5011249287053943
color:
  brandColors:
    - '#FFFFFF'
    - '#171718'
    - '#21303D'
    - '#D0B283'
    - '#515151'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
github: true
opengraph:
  image: 'http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png'
  type: website
  appId: '1517733501804443'
layout_spectrum: 1
analytics:
  google: UA-50607580-1
  facebook: '295556487279234'
  twitter: l4y05
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c8e3e03-5703-4144-9cbf-d85011b48d3c.svg
name: The Grid
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
navigation:
  - name: Blog
    url: 'https://blog.thegrid.io/'
    type: external
  - name: Support
    url: 'https://support.thegrid.io/'
    type: external
  - name: Login
    url: 'https://app.thegrid.io'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31a78343-dca7-494c-8e82-2a2b582bffc0.png
title: Join the Evolution
description: AI websites that design themselves
purpose:
  - type: external
    url: 'https://www.youtube.com/watch?v=aEfpARsP8Fg'
    label: Play Video
  - type: external
    url: 'https://plans.thegrid.io/pro/'
    label: Get on The Grid
